// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoaSpioguRX6jHzMAcbER2oHi5vjXpqI',
    appId: '1:669684729577:web:165ad9966a9eaa1d881278',
    messagingSenderId: '669684729577',
    projectId: 'uprides-1782f',
    authDomain: 'uprides-1782f.firebaseapp.com',
    storageBucket: 'uprides-1782f.firebasestorage.app',
    measurementId: 'G-7V4FS71Q3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-ElHwwwAMyJ9WNjDC1cLPaNxR3jkOCU',
    appId: '1:669684729577:android:4eea7d1954dd18c3881278',
    messagingSenderId: '669684729577',
    projectId: 'uprides-1782f',
    storageBucket: 'uprides-1782f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYIYy9KQvgI-3-Y6-0uFmHsjMr5w7g24',
    appId: '1:669684729577:ios:90d8c8f40b5d9397881278',
    messagingSenderId: '669684729577',
    projectId: 'uprides-1782f',
    storageBucket: 'uprides-1782f.firebasestorage.app',
    androidClientId: '669684729577-mh8ei8qdo72h0v89q3it65gugb8plrh8.apps.googleusercontent.com',
    iosClientId: '669684729577-7jnf5qjdk1b7q1rs38nu8vshb15l7vl2.apps.googleusercontent.com',
    iosBundleId: 'com.bold.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwYIYy9KQvgI-3-Y6-0uFmHsjMr5w7g24',
    appId: '1:669684729577:ios:90d8c8f40b5d9397881278',
    messagingSenderId: '669684729577',
    projectId: 'uprides-1782f',
    storageBucket: 'uprides-1782f.firebasestorage.app',
    androidClientId: '669684729577-mh8ei8qdo72h0v89q3it65gugb8plrh8.apps.googleusercontent.com',
    iosClientId: '669684729577-7jnf5qjdk1b7q1rs38nu8vshb15l7vl2.apps.googleusercontent.com',
    iosBundleId: 'com.bold.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdoaSpioguRX6jHzMAcbER2oHi5vjXpqI',
    appId: '1:669684729577:web:e05b7bac926098a0881278',
    messagingSenderId: '669684729577',
    projectId: 'uprides-1782f',
    authDomain: 'uprides-1782f.firebaseapp.com',
    storageBucket: 'uprides-1782f.firebasestorage.app',
    measurementId: 'G-2DEYDJFQTT',
  );
}
