// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcLnWLHVrbljhjx_9UzxcO6OYs6EXHVs',
    appId: '1:593584096267:android:12aff36905f3a2d6b2730e',
    messagingSenderId: '593584096267',
    projectId: 'bold-1d39b',
    storageBucket: 'bold-1d39b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzMzblKvDn_8EH8bukoY5INhXcNFVsuk',
    appId: '1:593584096267:ios:dd9de219afff2eaab2730e',
    messagingSenderId: '593584096267',
    projectId: 'bold-1d39b',
    storageBucket: 'bold-1d39b.firebasestorage.app',
    androidClientId: '593584096267-2mcn266g5tje3gbdtnst82aj9dbdg8d0.apps.googleusercontent.com',
    iosClientId: '593584096267-tri4kq0o35r3v5uj74e5ag1sajgb35ts.apps.googleusercontent.com',
    iosBundleId: 'com.bold.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTjWye2ChHTGsKhaVl9pkNFszW_MDGQnM',
    appId: '1:593584096267:web:e8c883f44e83ffefb2730e',
    messagingSenderId: '593584096267',
    projectId: 'bold-1d39b',
    authDomain: 'bold-1d39b.firebaseapp.com',
    storageBucket: 'bold-1d39b.appspot.com',
    measurementId: 'G-7HCWWWGWKT',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjWye2ChHTGsKhaVl9pkNFszW_MDGQnM',
    appId: '1:593584096267:web:21da7e7fd08df104b2730e',
    messagingSenderId: '593584096267',
    projectId: 'bold-1d39b',
    authDomain: 'bold-1d39b.firebaseapp.com',
    storageBucket: 'bold-1d39b.firebasestorage.app',
    measurementId: 'G-SMXVSX5WCJ',
  );

}