import '../../util/variable.dart';
import '../model/coordinate.dart';

const double halfPadding = 8;
const double p12 = 12;
const double spacing = 14;
const double horizontalSpacing = 15;
const double padding = 16;
const double p24 = 24;
const double boxHeight = 54;
const String apiKey = 'AIzaSyARa-NOfNmh-q2d097J0chrSUOjabg9EGc';
const Coordinate dummayLocation = Coordinate(latitude: 39.3999, longitude: 8.2245);
const List<int> tips = <int>[12, 24, 36];
//enum State { loading, data, error }
const String stripePublishableKey = 
// "pk_test_51PjKnU02fFDfZj1TYTBFujtlexl07K4wdMywxrnMpQ6CdvEoMlvQp03XQS9B1AN87PzpOxgNaWNQUIMwjFnHumdZ00b3fTDo9p";
'pk_live_51PjKnU02fFDfZj1TkkTBzY2q7mtiMwkJxnINNq20HH9ZMleHgE5IVvxx9T0LUVTjnq37tzaqqnaJp0zCZNMsShzZ00TlEWxjeq';
//const String stripeSecretKey = 'sk_test_51PjKnU02fFDfZj1TXZtCIpynyefQqmQuZ19GqYcaHik5ZeEjCesF0QpD7zY77CZstLA4U6kETR3XHWgsuEuP9Thn00mOiKGdfx';

const String closedToday = 'Closed today!';

const List<String> skippedImages = [
  "places/ChIJ1TtQlxy8Iw0RLNw6AJjz0vw/photos/ATKogpcfZtgAFmvWkjhlY0wTyApBOQXerihzcdJIPX_tpljRhWaP976hGPTOormemAAAtDG0BYA9UACY4pN-rpUbeu58shbmKMRiNwpdbT0pS0dtXoxRKHTIqW1D4tLBIEZypqedATqHib9kX3mIKwVVpFql32lhyrIDBUBwkC-LWH2t5FSsWxllEmktRpinlG2AjQPaezSNQ_ooan7dRdj-EGvfOAvZqnTmKGQtz4N69sNucqf7rZ6hWXXmy9vEE0p_tC8pIMjPstyiFt7g_3TSOjuepRxh_OyUeRMuqIZnHBl-hm4IxJ6q9gMt6DohJJJo_U9qOu_FEBDg4yVdQXju6r6voH3pR4X8U1W114h4OgZaIUr1bkvkxsoWd7CLpEA4QojPTo7at8W2sImvC9ZDPE0MjgDxKPI2_YO1aSigCPsQbiRy",
];
const String appStoreLink = "https://apps.apple.com/us/app/uprides/id6612036583";
const String playStoreLink = "https://play.google.com/store/apps/details?id=com.bold.customer";

const List<Map<String, String>> languages = [
  {'name': 'Português', 'code': 'pt', "en": "Portuguese"},
  {'name': 'English', 'code': 'en', "en": "English"},
  // {'name': 'Español', 'code': 'es',"en":"Spanish"},

  //  {'name': 'Italiano', 'code': 'it'},
  // {'name': 'Español', 'code': 'es'},
  // {'name': 'Deutsch', 'code': 'de'},
  // {'name': 'Français', 'code': 'fr'},
];

const Map<String, List<String>> trends = <String, List<String>>{
  'Cafe': <String>['cafe'],
  // 4. Nightlife
  'Nightlife': <String>[
    'bar',
    'bar_and_grill',
    'night_club',
    'pub',
    'wine_bar',
    'concert_hall',
    'comedy_club',
    'karaoke',
  ], // :contentReference[oaicite:4]{index=4}
  'Tourist Attractions': <String>[
    'tourist_attraction',
    'museum',
    'historical_landmark',
    'monument',
    'art_gallery',
    'aquarium',
    'zoo',
    'park',
    'national_park',
    'botanical_garden',
    'water_park',
    'amusement_park',
    'wildlife_park',
    'wildlife_refuge',
    'observation_deck',
    'plaza',
    'cultural_landmark',
  ], // :contentReference[oaicite:2]{index=2} :contentReference[oaicite:3]{index=3}
  // 'Attraction': <String>[
  //   'amusement_center',
  //   'amusement_park',
  //   'banquet_hall',
  //   'bowling_alley',
  //   'casino',
  //   'community_center',
  //   'convention_center',
  //   'cultural_center',
  //   'dog_park',
  //   'event_venue',
  //   'hiking_area',
  //   'historical_landmark',
  //   'movie_rental',
  //   'movie_theater',
  //   'national_park',
  //   'night_club',
  //   'park',
  //   'tourist_attraction',
  //   'visitor_center',
  //   'wedding_venue',
  //   'zoo',
  // ],

  // 2. Shopping
  'Shopping': <String>[
    'asian_grocery_store',
    'auto_parts_store',
    'bicycle_store',
    'book_store',
    'butcher_shop',
    'cell_phone_store',
    'clothing_store',
    'convenience_store',
    'department_store',
    'discount_store',
    'electronics_store',
    'food_store',
    'furniture_store',
    'gift_shop',
    'grocery_store',
    'hardware_store',
    'home_goods_store',
    'home_improvement_store',
    'jewelry_store',
    'liquor_store',
    'market',
    'pet_store',
    'shoe_store',
    'shopping_mall',
    'sporting_goods_store',
    'store',
    'supermarket',
    'warehouse_store',
    'wholesaler',
  ], // :contentReference[oaicite:1]{index=1}
  'Beach': <String>['tourist_attraction', 'marina', 'aquarium'],
  // 1. Restaurants
  'Restaurants': <String>[
    'afghani_restaurant',
    'african_restaurant',
    'american_restaurant',
    'asian_restaurant',
    'barbecue_restaurant',
    'brazilian_restaurant',
    'breakfast_restaurant',
    'brunch_restaurant',
    'buffet_restaurant',
    'chinese_restaurant',
    'dessert_restaurant',
    'diner',
    'fine_dining_restaurant',
    'french_restaurant',
    'greek_restaurant',
    'hamburger_restaurant',
    'indian_restaurant',
    'indonesian_restaurant',
    'italian_restaurant',
    'japanese_restaurant',
    'korean_restaurant',
    'lebanese_restaurant',
    'mediterranean_restaurant',
    'mexican_restaurant',
    'middle_eastern_restaurant',
    'pizza_restaurant',
    'ramen_restaurant',
    'seafood_restaurant',
    'spanish_restaurant',
    'steak_house',
    'sushi_restaurant',
    'thai_restaurant',
    'turkish_restaurant',
    'vegan_restaurant',
    'vegetarian_restaurant',
    'vietnamese_restaurant',
    'restaurant',
  ], // :contentReference[oaicite:0]{index=0}
  // 3. Tourist Attractions

  // 5. Outdoor & Adventure
  'Outdoor & Adventure': <String>[
    'hiking_area',
    'adventure_sports_center',
    'off_roading_area',
    'park',
    'national_park',
    // 'trail', // Note: 'trail' is in Table B but often used
    // 'natural_feature', // from Table B
  ], // :contentReference[oaicite:5]{index=5}
  // 6. Hotels & Accommodation
  'Hotels & Accommodation': <String>[
    'bed_and_breakfast',
    'budget_japanese_inn',
    'campground',
    'camping_cabin',
    'cottage',
    'extended_stay_hotel',
    'farmstay',
    'guest_house',
    'hostel',
    'hotel',
    'inn',
    'japanese_inn',
    'lodging',
    'mobile_home_park',
    'motel',
    'private_guest_room',
    'resort_hotel',
    'rv_park',
  ], // :contentReference[oaicite:6]{index=6}
  // 7. Health & Wellness
  'Health & Wellness': <String>['fitness_center', 'gym', 'spa', 'massage', 'yoga_studio', 'wellness_center'], // :contentReference[oaicite:7]{index=7}
  // 8. Transportation
  'Transportation': <String>[
    'airport',
    'international_airport',
    'train_station',
    'bus_station',
    'bus_stop',
    'taxi_stand',
    'ferry_terminal',
    'subway_station',
    'light_rail_station',
    'car_rental',
    'parking',
  ], // :contentReference[oaicite:8]{index=8}
  // your existing categories continue…
};

List<String> cancelRideReasons = <String>['I changed my mind', 'Fare is too high', 'Driver refused to come', 'Drivers behaviour was bad', l10n.other];

const List<String> addressTypes = <String>['Home', 'Office', 'Other'];
// const List<Map<String, String>> countries = [
//   {"code": "AF", "label": "Afghanistan", "phone": "93"},
//   {"code": "AL", "label": "Albania", "phone": "355"},
//   {"code": "DZ", "label": "Algeria", "phone": "213"},
//   {"code": "AD", "label": "Andorra", "phone": "376"},
//   {"code": "AO", "label": "Angola", "phone": "244"},
//   //{"code": "AG", "label": "Antigua and Barbuda", "phone": "1"},
//   {"code": "AR", "label": "Argentina", "phone": "54"},
//   {"code": "AM", "label": "Armenia", "phone": "374"},
//   {"code": "AU", "label": "Australia", "phone": "61"},
//   {"code": "AT", "label": "Austria", "phone": "43"},
//   {"code": "AZ", "label": "Azerbaijan", "phone": "994"},

//   /// {"code": "BS", "label": "Bahamas", "phone": "1"},
//   {"code": "BH", "label": "Bahrain", "phone": "973"},
//   {"code": "BD", "label": "Bangladesh", "phone": "880"},
//   // {"code": "BB", "label": "Barbados", "phone": "1"},
//   {"code": "BY", "label": "Belarus", "phone": "375"},
//   {"code": "BE", "label": "Belgium", "phone": "32"},
//   {"code": "BZ", "label": "Belize", "phone": "501"},
//   {"code": "BJ", "label": "Benin", "phone": "229"},
//   {"code": "BT", "label": "Bhutan", "phone": "975"},
//   {"code": "BO", "label": "Bolivia", "phone": "591"},
//   {"code": "BA", "label": "Bosnia and Herzegovina", "phone": "387"},
//   {"code": "BW", "label": "Botswana", "phone": "267"},
//   {"code": "BR", "label": "Brazil", "phone": "55"},
//   {"code": "BN", "label": "Brunei", "phone": "673"},
//   {"code": "BG", "label": "Bulgaria", "phone": "359"},
//   {"code": "BF", "label": "Burkina Faso", "phone": "226"},
//   {"code": "BI", "label": "Burundi", "phone": "257"},
//   {"code": "KH", "label": "Cambodia", "phone": "855"},
//   {"code": "CM", "label": "Cameroon", "phone": "237"},
//   // {"code": "CA", "label": "Canada", "phone": "1"},
//   {"code": "CV", "label": "Cape Verde", "phone": "238"},
//   {"code": "CF", "label": "Central African Republic", "phone": "236"},
//   {"code": "TD", "label": "Chad", "phone": "235"},
//   {"code": "CL", "label": "Chile", "phone": "56"},
//   {"code": "CN", "label": "China", "phone": "86"},
//   {"code": "CO", "label": "Colombia", "phone": "57"},
//   {"code": "KM", "label": "Comoros", "phone": "269"},
//   {"code": "CD", "label": "Congo (DRC)", "phone": "243"},
//   {"code": "CG", "label": "Congo (Republic)", "phone": "242"},
//   {"code": "CR", "label": "Costa Rica", "phone": "506"},
//   {"code": "HR", "label": "Croatia", "phone": "385"},
//   {"code": "CU", "label": "Cuba", "phone": "53"},
//   {"code": "CY", "label": "Cyprus", "phone": "357"},
//   {"code": "CZ", "label": "Czech Republic", "phone": "420"},
//   {"code": "DK", "label": "Denmark", "phone": "45"},
//   {"code": "DJ", "label": "Djibouti", "phone": "253"},
//   // {"code": "DM", "label": "Dominica", "phone": "1"},
//   //{"code": "DO", "label": "Dominican Republic", "phone": "1"},
//   {"code": "TL", "label": "Timor-Leste", "phone": "670"},
//   {"code": "EC", "label": "Ecuador", "phone": "593"},
//   {"code": "EG", "label": "Egypt", "phone": "20"},
//   {"code": "SV", "label": "El Salvador", "phone": "503"},
//   {"code": "GQ", "label": "Equatorial Guinea", "phone": "240"},
//   {"code": "ER", "label": "Eritrea", "phone": "291"},
//   {"code": "EE", "label": "Estonia", "phone": "372"},
//   {"code": "ET", "label": "Ethiopia", "phone": "251"},
//   {"code": "FJ", "label": "Fiji", "phone": "679"},
//   {"code": "FI", "label": "Finland", "phone": "358"},
//   {"code": "FR", "label": "France", "phone": "33"},
//   {"code": "GA", "label": "Gabon", "phone": "241"},
//   {"code": "GM", "label": "Gambia", "phone": "220"},
//   {"code": "GE", "label": "Georgia", "phone": "995"},
//   {"code": "DE", "label": "Germany", "phone": "49"},
//   {"code": "GH", "label": "Ghana", "phone": "233"},
//   {"code": "GR", "label": "Greece", "phone": "30"},
//   // {"code": "GD", "label": "Grenada", "phone": "1"},
//   {"code": "GT", "label": "Guatemala", "phone": "502"},
//   {"code": "GN", "label": "Guinea", "phone": "224"},
//   {"code": "GW", "label": "Guinea-Bissau", "phone": "245"},
//   {"code": "GY", "label": "Guyana", "phone": "592"},
//   {"code": "HT", "label": "Haiti", "phone": "509"},
//   {"code": "HN", "label": "Honduras", "phone": "504"},
//   {"code": "HU", "label": "Hungary", "phone": "36"},
//   {"code": "IS", "label": "Iceland", "phone": "354"},
//   {"code": "IN", "label": "India", "phone": "91"},
//   {"code": "ID", "label": "Indonesia", "phone": "62"},
//   {"code": "IR", "label": "Iran", "phone": "98"},
//   {"code": "IQ", "label": "Iraq", "phone": "964"},
//   {"code": "IE", "label": "Ireland", "phone": "353"},
//   {"code": "IL", "label": "Israel", "phone": "972"},
//   {"code": "IT", "label": "Italy", "phone": "39"},
// //  {"code": "JM", "label": "Jamaica", "phone": "1"},
//   {"code": "JP", "label": "Japan", "phone": "81"},
//   {"code": "JO", "label": "Jordan", "phone": "962"},
//   {"code": "KZ", "label": "Kazakhstan", "phone": "7"},
//   {"code": "KE", "label": "Kenya", "phone": "254"},
//   {"code": "KI", "label": "Kiribati", "phone": "686"},
//   {"code": "KW", "label": "Kuwait", "phone": "965"},
//   {"code": "KG", "label": "Kyrgyzstan", "phone": "996"},
//   {"code": "LA", "label": "Laos", "phone": "856"},
//   {"code": "LV", "label": "Latvia", "phone": "371"},
//   {"code": "LB", "label": "Lebanon", "phone": "961"},
//   {"code": "LS", "label": "Lesotho", "phone": "266"},
//   {"code": "LR", "label": "Liberia", "phone": "231"},
//   {"code": "LY", "label": "Libya", "phone": "218"},
//   {"code": "LI", "label": "Liechtenstein", "phone": "423"},
//   {"code": "LT", "label": "Lithuania", "phone": "370"},
//   {"code": "LU", "label": "Luxembourg", "phone": "352"},
//   {"code": "MG", "label": "Madagascar", "phone": "261"},
//   {"code": "MW", "label": "Malawi", "phone": "265"},
//   {"code": "MY", "label": "Malaysia", "phone": "60"},
//   {"code": "MV", "label": "Maldives", "phone": "960"},
//   {"code": "ML", "label": "Mali", "phone": "223"},
//   {"code": "MT", "label": "Malta", "phone": "356"},
//   {"code": "MH", "label": "Marshall Islands", "phone": "692"},
//   {"code": "MR", "label": "Mauritania", "phone": "222"},
//   {"code": "MU", "label": "Mauritius", "phone": "230"},
//   {"code": "MX", "label": "Mexico", "phone": "52"},
//   {"code": "FM", "label": "Micronesia", "phone": "691"},
//   {"code": "MD", "label": "Moldova", "phone": "373"},
//   {"code": "MC", "label": "Monaco", "phone": "377"},
//   {"code": "MN", "label": "Mongolia", "phone": "976"},
//   {"code": "ME", "label": "Montenegro", "phone": "382"},
//   {"code": "MA", "label": "Morocco", "phone": "212"},
//   {"code": "MZ", "label": "Mozambique", "phone": "258"},
//   {"code": "MM", "label": "Myanmar", "phone": "95"},
//   {"code": "NA", "label": "Namibia", "phone": "264"},
//   {"code": "NR", "label": "Nauru", "phone": "674"},
//   {"code": "NP", "label": "Nepal", "phone": "977"},
//   {"code": "NL", "label": "Netherlands", "phone": "31"},
//   {"code": "NZ", "label": "New Zealand", "phone": "64"},
//   {"code": "NI", "label": "Nicaragua", "phone": "505"},
//   {"code": "NE", "label": "Niger", "phone": "227"},
//   {"code": "NG", "label": "Nigeria", "phone": "234"},
//   {"code": "KP", "label": "North Korea", "phone": "850"},
//   {"code": "NO", "label": "Norway", "phone": "47"},
//   {"code": "OM", "label": "Oman", "phone": "968"},
//   {"code": "PK", "label": "Pakistan", "phone": "92"},
//   {"code": "PW", "label": "Palau", "phone": "680"},
//   {"code": "PA", "label": "Panama", "phone": "507"},
//   {"code": "PG", "label": "Papua New Guinea", "phone": "675"},
//   {"code": "PY", "label": "Paraguay", "phone": "595"},
//   {"code": "PE", "label": "Peru", "phone": "51"},
//   {"code": "PH", "label": "Philippines", "phone": "63"},
//   {"code": "PL", "label": "Poland", "phone": "48"},
//   {"code": "PT", "label": "Portugal", "phone": "351"},
//   {"code": "QA", "label": "Qatar", "phone": "974"},
//   {"code": "RO", "label": "Romania", "phone": "40"},
//   {"code": "RU", "label": "Russia", "phone": "7"},
//   {"code": "RW", "label": "Rwanda", "phone": "250"},
//   // {"code": "KN", "label": "Saint Kitts and Nevis", "phone": "1"},
//   // {"code": "LC", "label": "Saint Lucia", "phone": "1"},
//   // {"code": "VC", "label": "Saint Vincent and the Grenadines", "phone": "1"},
//   {"code": "WS", "label": "Samoa", "phone": "685"},
//   {"code": "SM", "label": "San Marino", "phone": "378"},
//   {"code": "ST", "label": "Sao Tome and Principe", "phone": "239"},
//   {"code": "SA", "label": "Saudi Arabia", "phone": "966"},
//   {"code": "SN", "label": "Senegal", "phone": "221"},
//   {"code": "RS", "label": "Serbia", "phone": "381"},
//   {"code": "SC", "label": "Seychelles", "phone": "248"},
//   {"code": "SL", "label": "Sierra Leone", "phone": "232"},
//   {"code": "SG", "label": "Singapore", "phone": "65"},
//   {"code": "SK", "label": "Slovakia", "phone": "421"},
//   {"code": "SI", "label": "Slovenia", "phone": "386"},
//   {"code": "SB", "label": "Solomon Islands", "phone": "677"},
//   {"code": "SO", "label": "Somalia", "phone": "252"},
//   {"code": "ZA", "label": "South Africa", "phone": "27"},
//   {"code": "KR", "label": "South Korea", "phone": "82"},
//   {"code": "SS", "label": "South Sudan", "phone": "211"},
//   {"code": "ES", "label": "Spain", "phone": "34"},
//   {"code": "LK", "label": "Sri Lanka", "phone": "94"},
//   {"code": "SD", "label": "Sudan", "phone": "249"},
//   {"code": "SR", "label": "Suriname", "phone": "597"},
//   {"code": "SZ", "label": "Swaziland", "phone": "268"},
//   {"code": "SE", "label": "Sweden", "phone": "46"},
//   {"code": "CH", "label": "Switzerland", "phone": "41"},
//   {"code": "SY", "label": "Syria", "phone": "963"},
//   {"code": "TW", "label": "Taiwan", "phone": "886"},
//   {"code": "TJ", "label": "Tajikistan", "phone": "992"},
//   {"code": "TZ", "label": "Tanzania", "phone": "255"},
//   {"code": "TH", "label": "Thailand", "phone": "66"},
//   {"code": "TG", "label": "Togo", "phone": "228"},
//   {"code": "TO", "label": "Tonga", "phone": "676"},
//   {"code": "TT", "label": "Trinidad and Tobago", "phone": "1"},
//   {"code": "TN", "label": "Tunisia", "phone": "216"},
//   {"code": "TR", "label": "Turkey", "phone": "90"},
//   {"code": "TM", "label": "Turkmenistan", "phone": "993"},
//   {"code": "TV", "label": "Tuvalu", "phone": "688"},
//   {"code": "UG", "label": "Uganda", "phone": "256"},
//   {"code": "UA", "label": "Ukraine", "phone": "380"},
//   {"code": "AE", "label": "United Arab Emirates", "phone": "971"},
//   {"code": "GB", "label": "United Kingdom", "phone": "44"},
//   {"code": "US", "label": "United States", "phone": "1"},
//   {"code": "UY", "label": "Uruguay", "phone": "598"},
//   {"code": "UZ", "label": "Uzbekistan", "phone": "998"},
//   {"code": "VU", "label": "Vanuatu", "phone": "678"},
//   {"code": "VA", "label": "Vatican City", "phone": "379"},
//   {"code": "VE", "label": "Venezuela", "phone": "58"},
//   {"code": "VN", "label": "Vietnam", "phone": "84"},
//   {"code": "YE", "label": "Yemen", "phone": "967"},
//   {"code": "ZM", "label": "Zambia", "phone": "260"},
//   {"code": "ZW", "label": "Zimbabwe", "phone": "263"},
// ];
const List<Map<String, String>> countries = <Map<String, String>>[
  <String, String>{'name': 'Afghanistan', 'dial_code': '+93', 'code': 'AF'},
  <String, String>{'name': 'Aland Islands', 'dial_code': '+358', 'code': 'AX'},
  <String, String>{'name': 'Albania', 'dial_code': '+355', 'code': 'AL'},
  <String, String>{'name': 'Algeria', 'dial_code': '+213', 'code': 'DZ'},
  <String, String>{'name': 'AmericanSamoa', 'dial_code': '+1684', 'code': 'AS'},
  <String, String>{'name': 'Andorra', 'dial_code': '+376', 'code': 'AD'},
  <String, String>{'name': 'Angola', 'dial_code': '+244', 'code': 'AO'},
  <String, String>{'name': 'Anguilla', 'dial_code': '+1264', 'code': 'AI'},
  <String, String>{'name': 'Antarctica', 'dial_code': '+672', 'code': 'AQ'},
  <String, String>{'name': 'Antigua and Barbuda', 'dial_code': '+1268', 'code': 'AG'},
  <String, String>{'name': 'Argentina', 'dial_code': '+54', 'code': 'AR'},
  <String, String>{'name': 'Armenia', 'dial_code': '+374', 'code': 'AM'},
  <String, String>{'name': 'Aruba', 'dial_code': '+297', 'code': 'AW'},
  <String, String>{'name': 'Australia', 'dial_code': '+61', 'code': 'AU'},
  <String, String>{'name': 'Austria', 'dial_code': '+43', 'code': 'AT'},
  <String, String>{'name': 'Azerbaijan', 'dial_code': '+994', 'code': 'AZ'},
  <String, String>{'name': 'Bahamas', 'dial_code': '+1242', 'code': 'BS'},
  <String, String>{'name': 'Bahrain', 'dial_code': '+973', 'code': 'BH'},
  <String, String>{'name': 'Bangladesh', 'dial_code': '+880', 'code': 'BD'},
  <String, String>{'name': 'Barbados', 'dial_code': '+1246', 'code': 'BB'},
  <String, String>{'name': 'Belarus', 'dial_code': '+375', 'code': 'BY'},
  <String, String>{'name': 'Belgium', 'dial_code': '+32', 'code': 'BE'},
  <String, String>{'name': 'Belize', 'dial_code': '+501', 'code': 'BZ'},
  <String, String>{'name': 'Benin', 'dial_code': '+229', 'code': 'BJ'},
  <String, String>{'name': 'Bermuda', 'dial_code': '+1441', 'code': 'BM'},
  <String, String>{'name': 'Bhutan', 'dial_code': '+975', 'code': 'BT'},
  <String, String>{'name': 'Bolivia, Plurinational State of', 'dial_code': '+591', 'code': 'BO'},
  <String, String>{'name': 'Bosnia and Herzegovina', 'dial_code': '+387', 'code': 'BA'},
  <String, String>{'name': 'Botswana', 'dial_code': '+267', 'code': 'BW'},
  <String, String>{'name': 'Brazil', 'dial_code': '+55', 'code': 'BR'},
  <String, String>{'name': 'British Indian Ocean Territory', 'dial_code': '+246', 'code': 'IO'},
  <String, String>{'name': 'Brunei Darussalam', 'dial_code': '+673', 'code': 'BN'},
  <String, String>{'name': 'Bulgaria', 'dial_code': '+359', 'code': 'BG'},
  <String, String>{'name': 'Burkina Faso', 'dial_code': '+226', 'code': 'BF'},
  <String, String>{'name': 'Burundi', 'dial_code': '+257', 'code': 'BI'},
  <String, String>{'name': 'Cambodia', 'dial_code': '+855', 'code': 'KH'},
  <String, String>{'name': 'Cameroon', 'dial_code': '+237', 'code': 'CM'},
  <String, String>{'name': 'Canada', 'dial_code': '+1', 'code': 'CA'},
  <String, String>{'name': 'Cape Verde', 'dial_code': '+238', 'code': 'CV'},
  <String, String>{'name': 'Cayman Islands', 'dial_code': '+ 345', 'code': 'KY'},
  <String, String>{'name': 'Central African Republic', 'dial_code': '+236', 'code': 'CF'},
  <String, String>{'name': 'Chad', 'dial_code': '+235', 'code': 'TD'},
  <String, String>{'name': 'Chile', 'dial_code': '+56', 'code': 'CL'},
  <String, String>{'name': 'China', 'dial_code': '+86', 'code': 'CN'},
  <String, String>{'name': 'Christmas Island', 'dial_code': '+61', 'code': 'CX'},
  <String, String>{'name': 'Cocos (Keeling) Islands', 'dial_code': '+61', 'code': 'CC'},
  <String, String>{'name': 'Colombia', 'dial_code': '+57', 'code': 'CO'},
  <String, String>{'name': 'Comoros', 'dial_code': '+269', 'code': 'KM'},
  <String, String>{'name': 'Congo', 'dial_code': '+242', 'code': 'CG'},
  <String, String>{'name': 'Congo, The Democratic Republic of the Congo', 'dial_code': '+243', 'code': 'CD'},
  <String, String>{'name': 'Cook Islands', 'dial_code': '+682', 'code': 'CK'},
  <String, String>{'name': 'Costa Rica', 'dial_code': '+506', 'code': 'CR'},
  <String, String>{'name': "Cote d'Ivoire", 'dial_code': '+225', 'code': 'CI'},
  <String, String>{'name': 'Croatia', 'dial_code': '+385', 'code': 'HR'},
  <String, String>{'name': 'Cuba', 'dial_code': '+53', 'code': 'CU'},
  <String, String>{'name': 'Cyprus', 'dial_code': '+357', 'code': 'CY'},
  <String, String>{'name': 'Czech Republic', 'dial_code': '+420', 'code': 'CZ'},
  <String, String>{'name': 'Denmark', 'dial_code': '+45', 'code': 'DK'},
  <String, String>{'name': 'Djibouti', 'dial_code': '+253', 'code': 'DJ'},
  <String, String>{'name': 'Dominica', 'dial_code': '+1767', 'code': 'DM'},
  <String, String>{'name': 'Dominican Republic', 'dial_code': '+1849', 'code': 'DO'},
  <String, String>{'name': 'Ecuador', 'dial_code': '+593', 'code': 'EC'},
  <String, String>{'name': 'Egypt', 'dial_code': '+20', 'code': 'EG'},
  <String, String>{'name': 'El Salvador', 'dial_code': '+503', 'code': 'SV'},
  <String, String>{'name': 'Equatorial Guinea', 'dial_code': '+240', 'code': 'GQ'},
  <String, String>{'name': 'Eritrea', 'dial_code': '+291', 'code': 'ER'},
  <String, String>{'name': 'Estonia', 'dial_code': '+372', 'code': 'EE'},
  <String, String>{'name': 'Ethiopia', 'dial_code': '+251', 'code': 'ET'},
  <String, String>{'name': 'Falkland Islands (Malvinas)', 'dial_code': '+500', 'code': 'FK'},
  <String, String>{'name': 'Faroe Islands', 'dial_code': '+298', 'code': 'FO'},
  <String, String>{'name': 'Fiji', 'dial_code': '+679', 'code': 'FJ'},
  <String, String>{'name': 'Finland', 'dial_code': '+358', 'code': 'FI'},
  <String, String>{'name': 'France', 'dial_code': '+33', 'code': 'FR'},
  <String, String>{'name': 'French Guiana', 'dial_code': '+594', 'code': 'GF'},
  <String, String>{'name': 'French Polynesia', 'dial_code': '+689', 'code': 'PF'},
  <String, String>{'name': 'Gabon', 'dial_code': '+241', 'code': 'GA'},
  <String, String>{'name': 'Gambia', 'dial_code': '+220', 'code': 'GM'},
  <String, String>{'name': 'Georgia', 'dial_code': '+995', 'code': 'GE'},
  <String, String>{'name': 'Germany', 'dial_code': '+49', 'code': 'DE'},
  <String, String>{'name': 'Ghana', 'dial_code': '+233', 'code': 'GH'},
  <String, String>{'name': 'Gibraltar', 'dial_code': '+350', 'code': 'GI'},
  <String, String>{'name': 'Greece', 'dial_code': '+30', 'code': 'GR'},
  <String, String>{'name': 'Greenland', 'dial_code': '+299', 'code': 'GL'},
  <String, String>{'name': 'Grenada', 'dial_code': '+1473', 'code': 'GD'},
  <String, String>{'name': 'Guadeloupe', 'dial_code': '+590', 'code': 'GP'},
  <String, String>{'name': 'Guam', 'dial_code': '+1671', 'code': 'GU'},
  <String, String>{'name': 'Guatemala', 'dial_code': '+502', 'code': 'GT'},
  <String, String>{'name': 'Guernsey', 'dial_code': '+44', 'code': 'GG'},
  <String, String>{'name': 'Guinea', 'dial_code': '+224', 'code': 'GN'},
  <String, String>{'name': 'Guinea-Bissau', 'dial_code': '+245', 'code': 'GW'},
  <String, String>{'name': 'Guyana', 'dial_code': '+595', 'code': 'GY'},
  <String, String>{'name': 'Haiti', 'dial_code': '+509', 'code': 'HT'},
  <String, String>{'name': 'Holy See (Vatican City State)', 'dial_code': '+379', 'code': 'VA'},
  <String, String>{'name': 'Honduras', 'dial_code': '+504', 'code': 'HN'},
  <String, String>{'name': 'Hong Kong', 'dial_code': '+852', 'code': 'HK'},
  <String, String>{'name': 'Hungary', 'dial_code': '+36', 'code': 'HU'},
  <String, String>{'name': 'Iceland', 'dial_code': '+354', 'code': 'IS'},
  <String, String>{'name': 'India', 'dial_code': '+91', 'code': 'IN'},
  <String, String>{'name': 'Indonesia', 'dial_code': '+62', 'code': 'ID'},
  <String, String>{'name': 'Iran, Islamic Republic of Persian Gulf', 'dial_code': '+98', 'code': 'IR'},
  <String, String>{'name': 'Iraq', 'dial_code': '+964', 'code': 'IQ'},
  <String, String>{'name': 'Ireland', 'dial_code': '+353', 'code': 'IE'},
  <String, String>{'name': 'Isle of Man', 'dial_code': '+44', 'code': 'IM'},
  <String, String>{'name': 'Israel', 'dial_code': '+972', 'code': 'IL'},
  <String, String>{'name': 'Italy', 'dial_code': '+39', 'code': 'IT'},
  <String, String>{'name': 'Jamaica', 'dial_code': '+1876', 'code': 'JM'},
  <String, String>{'name': 'Japan', 'dial_code': '+81', 'code': 'JP'},
  <String, String>{'name': 'Jersey', 'dial_code': '+44', 'code': 'JE'},
  <String, String>{'name': 'Jordan', 'dial_code': '+962', 'code': 'JO'},
  <String, String>{'name': 'Kazakhstan', 'dial_code': '+77', 'code': 'KZ'},
  <String, String>{'name': 'Kenya', 'dial_code': '+254', 'code': 'KE'},
  <String, String>{'name': 'Kiribati', 'dial_code': '+686', 'code': 'KI'},
  <String, String>{'name': "Korea, Democratic People's Republic of Korea", 'dial_code': '+850', 'code': 'KP'},
  <String, String>{'name': 'Korea, Republic of South Korea', 'dial_code': '+82', 'code': 'KR'},
  <String, String>{'name': 'Kuwait', 'dial_code': '+965', 'code': 'KW'},
  <String, String>{'name': 'Laos', 'dial_code': '+856', 'code': 'LA'},
  <String, String>{'name': 'Latvia', 'dial_code': '+371', 'code': 'LV'},
  <String, String>{'name': 'Lebanon', 'dial_code': '+961', 'code': 'LB'},
  <String, String>{'name': 'Lesotho', 'dial_code': '+266', 'code': 'LS'},
  <String, String>{'name': 'Liberia', 'dial_code': '+231', 'code': 'LR'},
  <String, String>{'name': 'Libyan Arab Jamahiriya', 'dial_code': '+218', 'code': 'LY'},
  <String, String>{'name': 'Liechtenstein', 'dial_code': '+423', 'code': 'LI'},
  <String, String>{'name': 'Lithuania', 'dial_code': '+370', 'code': 'LT'},
  <String, String>{'name': 'Luxembourg', 'dial_code': '+352', 'code': 'LU'},
  <String, String>{'name': 'Macao', 'dial_code': '+853', 'code': 'MO'},
  <String, String>{'name': 'Macedonia', 'dial_code': '+389', 'code': 'MK'},
  <String, String>{'name': 'Madagascar', 'dial_code': '+261', 'code': 'MG'},
  <String, String>{'name': 'Malawi', 'dial_code': '+265', 'code': 'MW'},
  <String, String>{'name': 'Malaysia', 'dial_code': '+60', 'code': 'MY'},
  <String, String>{'name': 'Maldives', 'dial_code': '+960', 'code': 'MV'},
  <String, String>{'name': 'Mali', 'dial_code': '+223', 'code': 'ML'},
  <String, String>{'name': 'Malta', 'dial_code': '+356', 'code': 'MT'},
  <String, String>{'name': 'Marshall Islands', 'dial_code': '+692', 'code': 'MH'},
  <String, String>{'name': 'Martinique', 'dial_code': '+596', 'code': 'MQ'},
  <String, String>{'name': 'Mauritania', 'dial_code': '+222', 'code': 'MR'},
  <String, String>{'name': 'Mauritius', 'dial_code': '+230', 'code': 'MU'},
  <String, String>{'name': 'Mayotte', 'dial_code': '+262', 'code': 'YT'},
  <String, String>{'name': 'Mexico', 'dial_code': '+52', 'code': 'MX'},
  <String, String>{'name': 'Micronesia, Federated States of Micronesia', 'dial_code': '+691', 'code': 'FM'},
  <String, String>{'name': 'Moldova', 'dial_code': '+373', 'code': 'MD'},
  <String, String>{'name': 'Monaco', 'dial_code': '+377', 'code': 'MC'},
  <String, String>{'name': 'Mongolia', 'dial_code': '+976', 'code': 'MN'},
  <String, String>{'name': 'Montenegro', 'dial_code': '+382', 'code': 'ME'},
  <String, String>{'name': 'Montserrat', 'dial_code': '+1664', 'code': 'MS'},
  <String, String>{'name': 'Morocco', 'dial_code': '+212', 'code': 'MA'},
  <String, String>{'name': 'Mozambique', 'dial_code': '+258', 'code': 'MZ'},
  <String, String>{'name': 'Myanmar', 'dial_code': '+95', 'code': 'MM'},
  <String, String>{'name': 'Namibia', 'dial_code': '+264', 'code': 'NA'},
  <String, String>{'name': 'Nauru', 'dial_code': '+674', 'code': 'NR'},
  <String, String>{'name': 'Nepal', 'dial_code': '+977', 'code': 'NP'},
  <String, String>{'name': 'Netherlands', 'dial_code': '+31', 'code': 'NL'},
  // {"name": "Netherlands Antilles", "dial_code": "+599", "code": "AN"},
  /// {"name": "New Caledonia", "dial_code": "+687", "code": "NC"},
  <String, String>{'name': 'New Zealand', 'dial_code': '+64', 'code': 'NZ'},
  // {"name": "Nicaragua", "dial_code": "+505", "code": "NI"},
  <String, String>{'name': 'Niger', 'dial_code': '+227', 'code': 'NE'},
  <String, String>{'name': 'Nigeria', 'dial_code': '+234', 'code': 'NG'},
  <String, String>{'name': 'Niue', 'dial_code': '+683', 'code': 'NU'},
  <String, String>{'name': 'Norfolk Island', 'dial_code': '+672', 'code': 'NF'},
  <String, String>{'name': 'Northern Mariana Islands', 'dial_code': '+1670', 'code': 'MP'},
  //  {"name": "Norway", "dial_code": "+47", "code": "NO"},
  //  {"name": "Oman", "dial_code": "+968", "code": "OM"},
  <String, String>{'name': 'Pakistan', 'dial_code': '+92', 'code': 'PK'},
  <String, String>{'name': 'Palau', 'dial_code': '+680', 'code': 'PW'},
  // {"name": "Palestinian Territory, Occupied", "dial_code": "+970", "code": "PS"},
  <String, String>{'name': 'Panama', 'dial_code': '+507', 'code': 'PA'},
  <String, String>{'name': 'Papua New Guinea', 'dial_code': '+675', 'code': 'PG'},
  <String, String>{'name': 'Paraguay', 'dial_code': '+595', 'code': 'PY'},
  <String, String>{'name': 'Peru', 'dial_code': '+51', 'code': 'PE'},
  <String, String>{'name': 'Philippines', 'dial_code': '+63', 'code': 'PH'},
  <String, String>{'name': 'Pitcairn', 'dial_code': '+872', 'code': 'PN'},
  <String, String>{'name': 'Poland', 'dial_code': '+48', 'code': 'PL'},
  <String, String>{'name': 'Portugal', 'dial_code': '+351', 'code': 'PT'},
  <String, String>{'name': 'Puerto Rico', 'dial_code': '+1939', 'code': 'PR'},
  <String, String>{'name': 'Qatar', 'dial_code': '+974', 'code': 'QA'},
  <String, String>{'name': 'Romania', 'dial_code': '+40', 'code': 'RO'},
  <String, String>{'name': 'Russia', 'dial_code': '+7', 'code': 'RU'},
  <String, String>{'name': 'Rwanda', 'dial_code': '+250', 'code': 'RW'},
  <String, String>{'name': 'Reunion', 'dial_code': '+262', 'code': 'RE'},
  <String, String>{'name': 'Saint Barthelemy', 'dial_code': '+590', 'code': 'BL'},
  <String, String>{'name': 'Saint Helena, Ascension and Tristan Da Cunha', 'dial_code': '+290', 'code': 'SH'},
  <String, String>{'name': 'Saint Kitts and Nevis', 'dial_code': '+1869', 'code': 'KN'},
  <String, String>{'name': 'Saint Lucia', 'dial_code': '+1758', 'code': 'LC'},
  <String, String>{'name': 'Saint Martin', 'dial_code': '+590', 'code': 'MF'},
  <String, String>{'name': 'Saint Pierre and Miquelon', 'dial_code': '+508', 'code': 'PM'},
  <String, String>{'name': 'Saint Vincent and the Grenadines', 'dial_code': '+1784', 'code': 'VC'},
  <String, String>{'name': 'Samoa', 'dial_code': '+685', 'code': 'WS'},
  <String, String>{'name': 'San Marino', 'dial_code': '+378', 'code': 'SM'},
  <String, String>{'name': 'Sao Tome and Principe', 'dial_code': '+239', 'code': 'ST'},
  <String, String>{'name': 'Saudi Arabia', 'dial_code': '+966', 'code': 'SA'},
  <String, String>{'name': 'Senegal', 'dial_code': '+221', 'code': 'SN'},
  <String, String>{'name': 'Serbia', 'dial_code': '+381', 'code': 'RS'},
  <String, String>{'name': 'Seychelles', 'dial_code': '+248', 'code': 'SC'},
  <String, String>{'name': 'Sierra Leone', 'dial_code': '+232', 'code': 'SL'},
  <String, String>{'name': 'Singapore', 'dial_code': '+65', 'code': 'SG'},
  <String, String>{'name': 'Slovakia', 'dial_code': '+421', 'code': 'SK'},
  <String, String>{'name': 'Slovenia', 'dial_code': '+386', 'code': 'SI'},
  <String, String>{'name': 'Solomon Islands', 'dial_code': '+677', 'code': 'SB'},
  <String, String>{'name': 'Somalia', 'dial_code': '+252', 'code': 'SO'},
  <String, String>{'name': 'South Africa', 'dial_code': '+27', 'code': 'ZA'},
  <String, String>{'name': 'South Sudan', 'dial_code': '+211', 'code': 'SS'},
  <String, String>{'name': 'South Georgia and the South Sandwich Islands', 'dial_code': '+500', 'code': 'GS'},
  <String, String>{'name': 'Spain', 'dial_code': '+34', 'code': 'ES'},
  <String, String>{'name': 'Sri Lanka', 'dial_code': '+94', 'code': 'LK'},
  <String, String>{'name': 'Sudan', 'dial_code': '+249', 'code': 'SD'},
  <String, String>{'name': 'Suriname', 'dial_code': '+597', 'code': 'SR'},
  <String, String>{'name': 'Svalbard and Jan Mayen', 'dial_code': '+47', 'code': 'SJ'},
  <String, String>{'name': 'Swaziland', 'dial_code': '+268', 'code': 'SZ'},
  <String, String>{'name': 'Sweden', 'dial_code': '+46', 'code': 'SE'},
  <String, String>{'name': 'Switzerland', 'dial_code': '+41', 'code': 'CH'},
  <String, String>{'name': 'Syrian Arab Republic', 'dial_code': '+963', 'code': 'SY'},
  <String, String>{'name': 'Taiwan', 'dial_code': '+886', 'code': 'TW'},
  <String, String>{'name': 'Tajikistan', 'dial_code': '+992', 'code': 'TJ'},
  <String, String>{'name': 'Tanzania, United Republic of Tanzania', 'dial_code': '+255', 'code': 'TZ'},
  <String, String>{'name': 'Thailand', 'dial_code': '+66', 'code': 'TH'},
  <String, String>{'name': 'Timor-Leste', 'dial_code': '+670', 'code': 'TL'},
  <String, String>{'name': 'Togo', 'dial_code': '+228', 'code': 'TG'},
  <String, String>{'name': 'Tokelau', 'dial_code': '+690', 'code': 'TK'},
  <String, String>{'name': 'Tonga', 'dial_code': '+676', 'code': 'TO'},
  <String, String>{'name': 'Trinidad and Tobago', 'dial_code': '+1868', 'code': 'TT'},
  <String, String>{'name': 'Tunisia', 'dial_code': '+216', 'code': 'TN'},
  <String, String>{'name': 'Turkey', 'dial_code': '+90', 'code': 'TR'},
  <String, String>{'name': 'Turkmenistan', 'dial_code': '+993', 'code': 'TM'},
  <String, String>{'name': 'Turks and Caicos Islands', 'dial_code': '+1649', 'code': 'TC'},
  <String, String>{'name': 'Tuvalu', 'dial_code': '+688', 'code': 'TV'},
  <String, String>{'name': 'Uganda', 'dial_code': '+256', 'code': 'UG'},
  <String, String>{'name': 'Ukraine', 'dial_code': '+380', 'code': 'UA'},
  <String, String>{'name': 'United Arab Emirates', 'dial_code': '+971', 'code': 'AE'},
  <String, String>{'name': 'United Kingdom', 'dial_code': '+44', 'code': 'GB'},
  <String, String>{'name': 'United States', 'dial_code': '+1', 'code': 'US'},
  <String, String>{'name': 'Uruguay', 'dial_code': '+598', 'code': 'UY'},
  <String, String>{'name': 'Uzbekistan', 'dial_code': '+998', 'code': 'UZ'},
  <String, String>{'name': 'Vanuatu', 'dial_code': '+678', 'code': 'VU'},
  <String, String>{'name': 'Venezuela, Bolivarian Republic of Venezuela', 'dial_code': '+58', 'code': 'VE'},
  <String, String>{'name': 'Vietnam', 'dial_code': '+84', 'code': 'VN'},
  <String, String>{'name': 'Virgin Islands, British', 'dial_code': '+1284', 'code': 'VG'},
  <String, String>{'name': 'Virgin Islands, U.S.', 'dial_code': '+1340', 'code': 'VI'},
  <String, String>{'name': 'Wallis and Futuna', 'dial_code': '+681', 'code': 'WF'},
  <String, String>{'name': 'Yemen', 'dial_code': '+967', 'code': 'YE'},
  <String, String>{'name': 'Zambia', 'dial_code': '+260', 'code': 'ZM'},
  <String, String>{'name': 'Zimbabwe', 'dial_code': '+263', 'code': 'ZW'},
];
const Map<String, String> countrymap = <String, String>{
  'AF': '93',
  'AL': '355',
  'DZ': '213',
  'AD': '376',
  'AO': '244',
  'AG': '1',
  'AR': '54',
  'AM': '374',
  'AU': '61',
  'AT': '43',
  'AZ': '994',
  'BS': '1',
  'BH': '973',
  'BD': '880',
  'BB': '1',
  'BY': '375',
  'BE': '32',
  'BZ': '501',
  'BJ': '229',
  'BT': '975',
  'BO': '591',
  'BA': '387',
  'BW': '267',
  'BR': '55',
  'BN': '673',
  'BG': '359',
  'BF': '226',
  'BI': '257',
  'KH': '855',
  'CM': '237',
  'CA': '1',
  'CV': '238',
  'CF': '236',
  'TD': '235',
  'CL': '56',
  'CN': '86',
  'CO': '57',
  'KM': '269',
  'CD': '243',
  'CG': '242',
  'CR': '506',
  'HR': '385',
  'CU': '53',
  'CY': '357',
  'CZ': '420',
  'DK': '45',
  'DJ': '253',
  'DM': '1',
  'DO': '1',
  'TL': '670',
  'EC': '593',
  'EG': '20',
  'SV': '503',
  'GQ': '240',
  'ER': '291',
  'EE': '372',
  'ET': '251',
  'FJ': '679',
  'FI': '358',
  'FR': '33',
  'GA': '241',
  'GM': '220',
  'GE': '995',
  'DE': '49',
  'GH': '233',
  'GR': '30',
  'GD': '1',
  'GT': '502',
  'GN': '224',
  'GW': '245',
  'GY': '592',
  'HT': '509',
  'HN': '504',
  'HU': '36',
  'IS': '354',
  'IN': '91',
  'ID': '62',
  'IR': '98',
  'IQ': '964',
  'IE': '353',
  'IL': '972',
  'IT': '39',
  'JM': '1',
  'JP': '81',
  'JO': '962',
  'KZ': '7',
  'KE': '254',
  'KI': '686',
  'KW': '965',
  'LA': '856',
  'LV': '371',
  'LB': '961',
  'LS': '266',
  'LR': '231',
  'LY': '218',
  'LI': '423',
  'LT': '370',
  'LU': '352',
  'MG': '261',
  'MW': '265',
  'MY': '60',
  'MV': '960',
  'ML': '223',
  'MT': '356',
  'MH': '692',
  'MR': '222',
  'MU': '230',
  'MX': '52',
  'FM': '691',
  'MD': '373',
  'MC': '377',
  'MN': '976',
  'ME': '382',
  'MA': '212',
  'MZ': '258',
  'MM': '95',
  'NA': '264',
  'NR': '674',
  'NP': '977',
  'NL': '31',
  'NZ': '64',
  'NI': '505',
  'NE': '227',
  'NG': '234',
  'KP': '850',
  'NO': '47',
  'OM': '968',
  'PK': '92',
  'PW': '680',
  'PA': '507',
  'PG': '675',
  'PY': '595',
  'PE': '51',
  'PH': '63',
  'PL': '48',
  'PT': '351',
  'QA': '974',
  'RO': '40',
  'RU': '7',
  'RW': '250',
  'KN': '1',
  'LC': '1',
  'VC': '1',
  'WS': '685',
  'SM': '378',
  'ST': '239',
  'SA': '966',
  'SN': '221',
  'RS': '381',
  'SC': '248',
  'SL': '232',
  'SG': '65',
  'SK': '421',
  'SI': '386',
  'SB': '677',
  'SO': '252',
  'ZA': '27',
  'KR': '82',
  'SS': '211',
  'ES': '34',
  'LK': '94',
  'SD': '249',
  'SR': '597',
  'SZ': '268',
  'SE': '46',
  'CH': '41',
  'SY': '963',
  'TW': '886',
  'TJ': '992',
  'TZ': '255',
  'TH': '66',
  'TG': '228',
  'TO': '676',
  'TT': '1',
  'TN': '216',
  'TR': '90',
  'TM': '993',
  'TV': '688',
  'UG': '256',
  'UA': '380',
  'AE': '971',
  'GB': '44',
  'US': '1',
  'UY': '598',
  'UZ': '998',
  'VU': '678',
  'VA': '379',
  'VE': '58',
  'VN': '84',
  'YE': '967',
  'ZM': '260',
  'ZW': '263',
};
